### ISSUE TITLE
Getting openai.error.APIError: HTTP code 502 from API

### ISSUE THREAD

**Issue by sganesan18** [louis-li/SqlGPT#7]
Retrying langchain.llms.openai.completion_with_retry.<locals>._completion_with_retry in 4.0 seconds as it raised APIError: HTTP code 502 from API ()

Getting the below error:
Traceback (most recent call last):
sqlgpt-main-application-1  |   File "/app/app.py", line 92, in api_answer
sqlgpt-main-application-1  |     answer, thought = sql_agent.run(question)
sqlgpt-main-application-1  |   File "/app/AzureOpenAIUtil/SqlServer.py", line 30, in run
sqlgpt-main-application-1  |     answer =  self.agent_executor.run(text)
sqlgpt-main-application-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 213, in run
sqlgpt-main-application-1  |     return self(args[0])[self.output_keys[0]]
sqlgpt-main-application-1  |   File "/usr/local/lib/python3.10/site-packages/langchain/chains/base.py", line 116, in __call_

**Comment by lixiaoyaois** [comment]
HTTP code 502 from API ()  大佬们这个怎么解决 我自己搭建的NLP模型要接入api接口
